<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Preferred payment was not specified</name>
   <tag></tag>
   <elementGuidId>93917814-591e-4612-9540-c884abfeb6d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountContainer']/div[4]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.mastercart.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0372a322-3576-4d44-8588-a4957d7efc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mastercart ng-scope</value>
      <webElementGuid>70017fc6-75f2-47b9-b5be-991599340a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Preferred_payment_has_not_been_set</value>
      <webElementGuid>35e8b4eb-dc1f-46d9-a180-ccfe8b9e58d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preferred payment was not specified</value>
      <webElementGuid>2144c191-9612-4b94-8736-a0dff0fec5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountContainer&quot;)/div[@class=&quot;cube&quot;]/div[@class=&quot;paymentBox&quot;]/label[@class=&quot;mastercart ng-scope&quot;]</value>
      <webElementGuid>340cd0b0-34be-4e52-b2ed-56c5d9c9a9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountContainer']/div[4]/div/label</value>
      <webElementGuid>23b1c327-fc34-4047-9aea-eb9960df8ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::label[1]</value>
      <webElementGuid>59cccbe3-dc52-4e11-bd62-a1f30213be96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MasterCredit'])[1]/preceding::label[1]</value>
      <webElementGuid>e7facb9f-d289-4770-9c18-dfacd0f5d02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='****'])[1]/preceding::label[2]</value>
      <webElementGuid>689e173c-f376-4472-92a1-e55b84455765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preferred payment was not specified']/parent::*</value>
      <webElementGuid>f659d8e5-a938-48da-bf6e-fac183248e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>6220aae7-6963-4143-85cf-85ef277ee66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Preferred payment was not specified' or . = 'Preferred payment was not specified')]</value>
      <webElementGuid>e659d1a2-f96d-4cbf-a73b-4d1af93b99a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
