<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Or</name>
   <tag></tag>
   <elementGuidId>de1220ea-c0df-410a-93b6-17863d53597b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInResultMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='signInResultMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c25adad1-5ea8-42cf-ad13-cb998b4af22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInResultMessage</value>
      <webElementGuid>0438cb60-37cf-4f52-aa90-c815e7b24222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>or  center</value>
      <webElementGuid>78119aab-db70-41f8-b9ca-7810218121d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OR</value>
      <webElementGuid>ffd8c22f-3bfd-440c-9f94-c636f54625d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInResultMessage&quot;)</value>
      <webElementGuid>d0f0008d-39e5-4ffe-8e0e-2156b95d1d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='signInResultMessage']</value>
      <webElementGuid>015b57b5-80b9-4242-ba67-f7b8edb26f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN WITH FACEBOOK'])[1]/following::label[1]</value>
      <webElementGuid>bfc6e930-9368-4201-ac71-cc6dae5f0a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[2]/preceding::label[1]</value>
      <webElementGuid>bfd4eef2-4f9f-4e2c-9c99-b855240a474d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/preceding::label[2]</value>
      <webElementGuid>83e414e4-96c4-461a-bd30-f176d546464c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OR']/parent::*</value>
      <webElementGuid>5ab1bd88-6e7c-4df1-9bc4-873839dca93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>ef981c3e-755b-499e-a122-b58077b896dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'signInResultMessage' and (text() = 'OR' or . = 'OR')]</value>
      <webElementGuid>00a93d9e-0117-433f-8b2a-ac639df6ff0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
