<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CardNumber</name>
   <tag></tag>
   <elementGuidId>f0922cde-04d7-4ab6-b516-dcc04463cbb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58594cf4-2053-41d3-92d1-401f40e4e781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCard</value>
      <webElementGuid>a0ecc2f6-0fda-4ea3-88da-f886c54bea2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>83ac3034-b819-41c7-9e99-d3cde3965483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>924354b9-afd5-457a-ba17-99c89918e17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>40deccca-f169-46a3-8221-425599fbe76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope ng-valid-maxlength</value>
      <webElementGuid>6a1f844b-ab9e-48a3-aa00-4cbd8360b12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCard&quot;)</value>
      <webElementGuid>db85cca0-637a-42d3-90fe-621c65e382e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCard']</value>
      <webElementGuid>a0c4a3a8-fd1b-4349-b510-0660a617bb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>07803d90-95bd-472f-954c-66fbe04e6e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>8fc7cfe6-2507-494d-bf1a-247c6dbd305c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'creditCard' and @name = 'card_number']</value>
      <webElementGuid>45e68be5-1dc0-4d05-a756-e7e089955bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
