<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_CVV number</name>
   <tag></tag>
   <elementGuidId>ff7d56db-2fce-4d45-847c-1962fdee9d79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sec-view.creditCard.ng-isolate-scope.sec-view > div.inputContainer.ng-scope > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div/sec-view[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>aedc93d9-9caa-4fcb-9f64-bf65740fa459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>labelClicked()</value>
      <webElementGuid>12b49fc1-d59b-41e7-a54f-0711f05802e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mouseout</name>
      <type>Main</type>
      <value>labelOut()</value>
      <webElementGuid>004ad7c2-1867-4d94-ad33-c8bbdbbb71b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CVV number</value>
      <webElementGuid>60208ee7-59b5-4baf-bb88-635813b0cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[4]/sec-form[@class=&quot;ng-isolate-scope secForm&quot;]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;creditCard ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/label[1]</value>
      <webElementGuid>9fb49b14-64b0-430e-9a72-44733550fe2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div/sec-view[2]/div/label</value>
      <webElementGuid>9e8e0242-e213-4d7e-8a93-3f1337c3c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::label[1]</value>
      <webElementGuid>02c9eb71-56d3-4fa7-bca6-903aa2500570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Use exactly 16 numbers'])[1]/following::label[1]</value>
      <webElementGuid>f3f807e8-5c91-4d70-b928-fa1f34f7781e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Use exactly 3 digits'])[1]/preceding::label[1]</value>
      <webElementGuid>ee556df6-81e1-4dcc-8109-beb70caf1af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration date'])[1]/preceding::label[1]</value>
      <webElementGuid>17e5f486-b0ac-4f3b-ad32-f067d1a9a125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sec-form/div/sec-view[2]/div/label</value>
      <webElementGuid>0261235c-ef3a-4833-9ced-c02ba07a9ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'CVV number' or . = 'CVV number')]</value>
      <webElementGuid>4c20a527-f321-49a2-9ff0-0a8d668d971c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
