<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_1,009.00</name>
   <tag></tag>
   <elementGuidId>c9819fe8-17a7-44f4-90ae-7ce99fbc6f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.productPrice.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'$1,009.00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>125fc831-4e25-4cbe-a1a4-e5ac81ba45ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productPrice ng-binding</value>
      <webElementGuid>7196e64b-c827-4fb9-9ede-234460ae1ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1,009.00 </value>
      <webElementGuid>9989144b-1054-43e6-8412-4c6b5f914f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;uiview ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/article[1]/div[3]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;category-type-products ng-isolate-scope&quot;]/div[@class=&quot;cell categoryRight&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/p[2]/a[@class=&quot;productPrice ng-binding&quot;]</value>
      <webElementGuid>17d10715-ca88-4562-92c7-af64d671b3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'$1,009.00')]</value>
      <webElementGuid>20b957d8-3ba2-4290-b840-d0bb151fe2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP ElitePad 1000 G2 Tablet'])[1]/following::a[1]</value>
      <webElementGuid>e4e22d8f-8f97-4789-b343-f347f6e6b612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP NOW'])[1]/following::a[2]</value>
      <webElementGuid>31023101-92f1-4c77-b65d-d1c0b3b1c737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/preceding::a[1]</value>
      <webElementGuid>5f6e4a83-8927-4449-90d3-4a1edab88935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP NOW'])[2]/preceding::a[1]</value>
      <webElementGuid>c4a5b330-780f-491e-abc5-bb9ae74eeefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1,009.00']/parent::*</value>
      <webElementGuid>934525a8-9ad3-4f15-bd33-927d77b73848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>a5ad140e-67c8-4c05-9d8d-0213fae6fdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '$1,009.00 ' or . = '$1,009.00 ')]</value>
      <webElementGuid>4e885ff7-a52b-4d94-80e6-59e214e639d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
