<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Display</name>
   <tag></tag>
   <elementGuidId>9a67bf21-d976-4aa8-af3f-8cc1223651aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordionAttrib0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionAttrib0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c2060876-8969-49d0-9601-b05133a8ccaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>7e9d131a-60fa-4342-8e00-d8497206414c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-binding</value>
      <webElementGuid>b6a18fb7-66ee-4394-994d-e50f672a3ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionAttrib0</value>
      <webElementGuid>167b799d-652d-4f6d-9f4e-3afd421ebd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionAttrib' + $index)</value>
      <webElementGuid>68c37b78-bf59-4b63-bd7f-7cdcbf11e5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>1f884fab-48fd-4810-8389-b0433c5f10f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DISPLAY
                    </value>
      <webElementGuid>7342de60-68e9-4d2b-947e-f21bb85051bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionAttrib0&quot;)</value>
      <webElementGuid>67fc3e93-620d-4ea4-8e40-11108aea8753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionAttrib0']</value>
      <webElementGuid>b9e6a9e2-fa85-4437-be36-d1cbbaff64b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[2]/h4</value>
      <webElementGuid>6423f6e7-3856-41c7-9f47-3759f5b65928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRICE'])[1]/following::h4[1]</value>
      <webElementGuid>fcbf6b28-6a55-433f-9990-cde4130f6023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::h4[2]</value>
      <webElementGuid>f5e12660-ea93-4be4-bc7c-8bafd22ebfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('7.9', '&quot;', ' diagonal FHD multi-touch display with Corning® Gorilla® Glass® (2048 x 1536)')])[1]/preceding::h4[1]</value>
      <webElementGuid>6e66d310-f398-4dc1-9e59-6bf0b5d59f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCESSOR'])[1]/preceding::h4[1]</value>
      <webElementGuid>d957f9d1-e46f-438e-aac0-a38069d382e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DISPLAY']/parent::*</value>
      <webElementGuid>58529715-e703-4dff-a717-75f663dabe88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/h4</value>
      <webElementGuid>ebd403d0-dc28-4528-be83-6e4bd45cd1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionAttrib0' and (text() = '
                        DISPLAY
                    ' or . = '
                        DISPLAY
                    ')]</value>
      <webElementGuid>325f0336-ec0f-4fe8-80f1-7a088f4cbd19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
