<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Price</name>
   <tag></tag>
   <elementGuidId>b924b808-cb94-412e-8333-e3fa409f81c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordionPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>38e2f152-6c62-4a86-a84b-4699655e5b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>06ff0153-955e-4c89-afb6-44225ddad9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-scope</value>
      <webElementGuid>34db9a3f-3a81-40db-9b10-974f13c4d722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionPrice</value>
      <webElementGuid>4ccae3fc-0c17-4227-96ea-7508020133dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionPrice')</value>
      <webElementGuid>ebcbd505-aef2-42ba-9e78-bf55dc4a0f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>PRICE</value>
      <webElementGuid>757771f0-4cd0-4c59-b9de-8c82a49f18c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>70522ed3-59fa-4d9b-8873-3b0667f37e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRICE</value>
      <webElementGuid>a83ffc34-212e-4f4c-a3de-110829e01d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionPrice&quot;)</value>
      <webElementGuid>f7626273-8515-4d74-9dac-216d2fe3e18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionPrice']</value>
      <webElementGuid>c52bd233-4020-43c4-ab22-4269a70e207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li/h4</value>
      <webElementGuid>f2b88ef5-3690-4261-8bd8-b65e7589cbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::h4[1]</value>
      <webElementGuid>f5c09db8-cb11-4713-9c9d-9f480e3b3c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY'])[1]/preceding::h4[1]</value>
      <webElementGuid>a4e7b5b0-6b6b-490d-9a1e-3bb67deef3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('7.9', '&quot;', ' diagonal FHD multi-touch display with Corning® Gorilla® Glass® (2048 x 1536)')])[1]/preceding::h4[2]</value>
      <webElementGuid>184bbbc2-86b0-4b37-937b-4839f7fa8152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRICE']/parent::*</value>
      <webElementGuid>18010c68-440e-4176-8643-4b9c64fe8e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>011899d3-5036-49cd-825b-173816a17603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionPrice' and (text() = 'PRICE' or . = 'PRICE')]</value>
      <webElementGuid>4b5d4a56-8af8-42ef-ae89-c650f68336c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
