<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Processor</name>
   <tag></tag>
   <elementGuidId>050f0aa0-5404-453b-ac06-50bb2ef6e58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordionAttrib1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionAttrib1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>b17cc052-a186-4db8-8c2a-402b6874e8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>65925e7e-c7f5-460c-aa69-589807c29c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-binding</value>
      <webElementGuid>f85da162-1713-4ade-8d70-4150e242bb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionAttrib1</value>
      <webElementGuid>50662870-f19a-4831-8757-213657b73c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionAttrib' + $index)</value>
      <webElementGuid>796ef836-2352-436b-b2cc-29fe37f60173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>1d13b8d4-016a-4ebf-b3cf-beadb318ba80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        PROCESSOR
                    </value>
      <webElementGuid>59c58e1a-8f54-4279-b060-0d8ae3b73c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionAttrib1&quot;)</value>
      <webElementGuid>13f61e69-c2c9-4609-a383-96af0e054656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionAttrib1']</value>
      <webElementGuid>e53901c5-ef0c-4c57-95c8-4ab8c4148a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/h4</value>
      <webElementGuid>7c6ab090-65f5-4cf4-b4e8-9ba7e96a663c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('7.9', '&quot;', ' diagonal FHD multi-touch display with Corning® Gorilla® Glass® (2048 x 1536)')])[1]/following::h4[1]</value>
      <webElementGuid>6f514b1e-18b6-408d-b804-c2ff9462235b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY'])[1]/following::h4[1]</value>
      <webElementGuid>2467c2c4-871f-45ec-9fef-941b705523ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intel® Atom® Z3795 (1.6 GHz, up to 2.39 GHz using Intel Burst Technology, 2 MB cache, 4 cores)'])[1]/preceding::h4[1]</value>
      <webElementGuid>568d56bd-ddaf-44ca-9a95-8ccb4a1b7846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOR'])[1]/preceding::h4[1]</value>
      <webElementGuid>09fe9a0b-1e73-4c11-94e8-315907bc45d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCESSOR']/parent::*</value>
      <webElementGuid>b8458b9f-c086-463a-b3db-3992cf07b5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/h4</value>
      <webElementGuid>7d2b71d1-f545-48a7-91c9-660dfdf8d26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionAttrib1' and (text() = '
                        PROCESSOR
                    ' or . = '
                        PROCESSOR
                    ')]</value>
      <webElementGuid>5c5ed0ce-3aae-4c35-b413-d767e7ec27b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
