<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Checkout(price)</name>
   <tag></tag>
   <elementGuidId>e9689039-fb21-445e-bb35-c0a2bf432b56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutPopUp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutPopUp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6534d1c7-17e4-41b5-b306-710cd4085d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutPopUp</value>
      <webElementGuid>33d76c80-2a3b-4198-b729-c4b3226ba168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>360c5149-598c-45ea-93c8-f7863717eba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9fb451c-dd00-420c-8806-a73d3f73cb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-binding</value>
      <webElementGuid>0b20a5d4-2adb-4877-be5a-a8853652be19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout($event)</value>
      <webElementGuid>9f2266af-559e-4516-8e2d-e6246292b552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT  ($1,009.00)</value>
      <webElementGuid>52825f0d-3378-4697-b4b4-c9870f3038ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutPopUp&quot;)</value>
      <webElementGuid>839dcb8c-9e93-4406-97b6-90427646e8c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutPopUp']</value>
      <webElementGuid>cbda1579-c369-4132-b5d1-e464c2673443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tool-tip-cart[@id='toolTipCart']/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>50d3acaf-c263-4932-bfd5-beb1b0b58713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,009.00'])[2]/following::button[1]</value>
      <webElementGuid>7adb9f09-338b-4ccf-9a25-81249a886b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 Item)'])[1]/following::button[1]</value>
      <webElementGuid>b215f6d4-c86b-4676-bbdc-80f9bbb51257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drinatest'])[2]/preceding::button[1]</value>
      <webElementGuid>fb178d4d-0855-4a66-a0dc-feb557ab0838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::button[1]</value>
      <webElementGuid>ecab734f-3a97-4231-ae6a-0803a27eca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button</value>
      <webElementGuid>a26ebbf2-8acd-4eb5-a2a5-3408c683252d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutPopUp' and @name = 'check_out_btn' and (text() = 'CHECKOUT  ($1,009.00)' or . = 'CHECKOUT  ($1,009.00)')]</value>
      <webElementGuid>36bdf89a-b366-4a9b-8c24-fe462455f845</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
