<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_tablet</name>
   <tag></tag>
   <elementGuidId>68ff26d2-8db6-43ac-9464-904cc69cc437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='mainImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f5ad243-18e9-481e-a687-9a65e33d41b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainImg</value>
      <webElementGuid>aafc9487-4b2b-4fbe-b2fd-48e890c01220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3100</value>
      <webElementGuid>d3b83df9-d0cd-40d9-8d3a-feb9f595c052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3100</value>
      <webElementGuid>d6d3cb36-8a5b-49df-894e-171e06115622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainImg&quot;)</value>
      <webElementGuid>0587dbe5-7b57-4c5d-b50c-1487e1b6075b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='mainImg']</value>
      <webElementGuid>38c85c19-1914-430b-92a8-4dfb7964d416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-section']/figure/img</value>
      <webElementGuid>e85188bb-48e2-4e4e-b7a1-ea93bdd6241d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>a7852c9a-b0ec-4933-90ec-a645d50385ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'mainImg' and @src = '/catalog/fetchImage?image_id=3100']</value>
      <webElementGuid>171a2322-3849-4991-83a9-38f585ce700d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
