<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Thank you for buying with Advantage</name>
   <tag></tag>
   <elementGuidId>cc42374a-6dfd-4993-8750-5d2ae2e0e4f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderPaymentSuccess']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>97a87e49-4c79-47d4-ac25-4bd25776f340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Thank you for buying with Advantage </value>
      <webElementGuid>70441d3d-e94d-4d57-b699-26c0fafcbdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderPaymentSuccess&quot;)/h2[1]</value>
      <webElementGuid>e91968ad-14f5-4d9f-9387-6ab16c6ac8c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderPaymentSuccess']/h2</value>
      <webElementGuid>fe3bb48b-452b-4fa4-bc63-133579539053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[4]/following::h2[1]</value>
      <webElementGuid>fbf70c20-c9e7-4824-9b75-16dd06f96a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::h2[1]</value>
      <webElementGuid>c4152bd3-5fb6-4a5e-9575-b22f39bad4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>aa1f9c78-fdb9-48f4-b900-7caaf95ba31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = ' Thank you for buying with Advantage ' or . = ' Thank you for buying with Advantage ')]</value>
      <webElementGuid>9af6ab93-7628-4604-9fdb-d3719fefc1f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
