<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_HP ELITEPAD 1000 G2 TABLET</name>
   <tag></tag>
   <elementGuidId>fae2cb03-4353-4a61-9672-a2b6a02e1a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.roboto-regular.screen768.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Description']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>945699a1-c010-42ea-968b-e660ca17743f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular screen768 ng-binding</value>
      <webElementGuid>dcb08278-58b9-448f-86e2-a87235fb5458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> HP ELITEPAD 1000 G2 TABLET </value>
      <webElementGuid>38cb9795-e676-46d1-bda5-49c21b487049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)/h1[@class=&quot;roboto-regular screen768 ng-binding&quot;]</value>
      <webElementGuid>d86e4a8a-e5d5-4b2d-8213-443295a6e46d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Description']/h1</value>
      <webElementGuid>b7c76cb1-eb57-44c5-90db-f897ce7bca0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[1]/following::h1[1]</value>
      <webElementGuid>bdc2cd13-d8f7-4b83-ba56-8d2fc4027cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[2]/preceding::h1[1]</value>
      <webElementGuid>f02e3022-b24e-4e7c-a5f9-6c7e97f8c48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h1</value>
      <webElementGuid>cf755d44-0e8c-41a2-b10c-943d4c365bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' HP ELITEPAD 1000 G2 TABLET ' or . = ' HP ELITEPAD 1000 G2 TABLET ')]</value>
      <webElementGuid>e67363c1-6cff-402d-a7b8-d5b6215f2440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
