<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Speakers</name>
   <tag></tag>
   <elementGuidId>eee5d127-6d52-4a46-b5f6-98407dcd8b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#speakersImg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='speakersImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b768f91-79da-43e8-9868-bce5acdce88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>speakersImg</value>
      <webElementGuid>db9d8a76-ddd5-4fcd-ad1d-6c49a429998c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SpeakersCategory</value>
      <webElementGuid>9f465436-4845-4873-989c-28e467c1ce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>redirect('/category/' + categories[3].categoryName + '/' + categories[3].categoryId)</value>
      <webElementGuid>57ef1b6e-f779-4e43-9d68-52d7d2bd385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>b5779073-b398-40db-8d94-893baeb2c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>46f4e316-c831-41b6-9808-a581191cc1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SpeakersImg categoryCell</value>
      <webElementGuid>520683c6-6bb6-4115-87b9-0cd42bca4b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-sec-back-img</name>
      <type>Main</type>
      <value>speakers</value>
      <webElementGuid>b9160777-a51d-4213-b6f2-07674f1854e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a-slow-page</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce1affd9-fcc9-4982-bf7c-ab3d71469900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                        SPEAKERS
                        Shop Now
                    
                </value>
      <webElementGuid>1a512588-0362-43a2-bfe2-fb6ce67552ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;speakersImg&quot;)</value>
      <webElementGuid>cbea0eb6-8172-4749-b72c-25d58d039d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='speakersImg']</value>
      <webElementGuid>5cc50f28-d31b-46e3-8209-3e5d27596f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='our_products']/div[2]/div/div</value>
      <webElementGuid>0839f286-3efc-4f78-9798-a6a435274c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEMO'])[1]/following::div[8]</value>
      <webElementGuid>80f5d2b8-d08c-4635-b501-04b7ecc39de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dvantage'])[1]/following::div[8]</value>
      <webElementGuid>6c58f5c3-d3b7-40d4-bde1-230c8924e87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div[2]/div/div</value>
      <webElementGuid>17a00299-3c86-4871-92a7-1e09ed87def1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'speakersImg' and @href = 'javascript:void(0)' and (text() = '
                    
                        SPEAKERS
                        Shop Now
                    
                ' or . = '
                    
                        SPEAKERS
                        Shop Now
                    
                ')]</value>
      <webElementGuid>30253e43-73a1-406c-903b-b93c335f0adc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
